/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as AuthorBooksIndexRouteImport } from './routes/author/books/index'
import { Route as AuthorBooksNewRouteImport } from './routes/author/books/new'
import { Route as AuthorBooksBookIdEditRouteImport } from './routes/author/books/$bookId/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/library/index.lazy').then((d) => d.Route))
const AuthorBooksIndexRoute = AuthorBooksIndexRouteImport.update({
  id: '/author/books/',
  path: '/author/books/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/author/books/index.lazy').then((d) => d.Route),
)
const AuthorBooksNewRoute = AuthorBooksNewRouteImport.update({
  id: '/author/books/new',
  path: '/author/books/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/author/books/new.lazy').then((d) => d.Route),
)
const AuthorBooksBookIdEditRoute = AuthorBooksBookIdEditRouteImport.update({
  id: '/author/books/$bookId/edit',
  path: '/author/books/$bookId/edit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/author/books/$bookId/edit.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/library/': typeof LibraryIndexRoute
  '/author/books/new': typeof AuthorBooksNewRoute
  '/author/books/': typeof AuthorBooksIndexRoute
  '/author/books/$bookId/edit': typeof AuthorBooksBookIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/library': typeof LibraryIndexRoute
  '/author/books/new': typeof AuthorBooksNewRoute
  '/author/books': typeof AuthorBooksIndexRoute
  '/author/books/$bookId/edit': typeof AuthorBooksBookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/library/': typeof LibraryIndexRoute
  '/author/books/new': typeof AuthorBooksNewRoute
  '/author/books/': typeof AuthorBooksIndexRoute
  '/author/books/$bookId/edit': typeof AuthorBooksBookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/library/'
    | '/author/books/new'
    | '/author/books/'
    | '/author/books/$bookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/library'
    | '/author/books/new'
    | '/author/books'
    | '/author/books/$bookId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/library/'
    | '/author/books/new'
    | '/author/books/'
    | '/author/books/$bookId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  AuthorBooksNewRoute: typeof AuthorBooksNewRoute
  AuthorBooksIndexRoute: typeof AuthorBooksIndexRoute
  AuthorBooksBookIdEditRoute: typeof AuthorBooksBookIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/books/': {
      id: '/author/books/'
      path: '/author/books'
      fullPath: '/author/books/'
      preLoaderRoute: typeof AuthorBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/books/new': {
      id: '/author/books/new'
      path: '/author/books/new'
      fullPath: '/author/books/new'
      preLoaderRoute: typeof AuthorBooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/books/$bookId/edit': {
      id: '/author/books/$bookId/edit'
      path: '/author/books/$bookId/edit'
      fullPath: '/author/books/$bookId/edit'
      preLoaderRoute: typeof AuthorBooksBookIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  AuthorBooksNewRoute: AuthorBooksNewRoute,
  AuthorBooksIndexRoute: AuthorBooksIndexRoute,
  AuthorBooksBookIdEditRoute: AuthorBooksBookIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
