/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as ReaderBookIdRouteImport } from './routes/reader/$bookId'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as AuthorBooksIndexRouteImport } from './routes/author/books/index'
import { Route as AuthorBooksNewRouteImport } from './routes/author/books/new'
import { Route as AuthorBooksBookIdEditRouteImport } from './routes/author/books/$bookId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/register/index.lazy').then((d) => d.Route),
)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/library/index.lazy').then((d) => d.Route))
const ReaderBookIdRoute = ReaderBookIdRouteImport.update({
  id: '/reader/$bookId',
  path: '/reader/$bookId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reader/$bookId.lazy').then((d) => d.Route),
)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/books/$bookId.lazy').then((d) => d.Route))
const AuthorBooksIndexRoute = AuthorBooksIndexRouteImport.update({
  id: '/author/books/',
  path: '/author/books/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/author/books/index.lazy').then((d) => d.Route),
)
const AuthorBooksNewRoute = AuthorBooksNewRouteImport.update({
  id: '/author/books/new',
  path: '/author/books/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/author/books/new.lazy').then((d) => d.Route),
)
const AuthorBooksBookIdEditRoute = AuthorBooksBookIdEditRouteImport.update({
  id: '/author/books/$bookId/edit',
  path: '/author/books/$bookId/edit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/author/books/$bookId/edit.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/library/': typeof LibraryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/author/books/new': typeof AuthorBooksNewRoute
  '/author/books/': typeof AuthorBooksIndexRoute
  '/author/books/$bookId/edit': typeof AuthorBooksBookIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/library': typeof LibraryIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/author/books/new': typeof AuthorBooksNewRoute
  '/author/books': typeof AuthorBooksIndexRoute
  '/author/books/$bookId/edit': typeof AuthorBooksBookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/library/': typeof LibraryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/author/books/new': typeof AuthorBooksNewRoute
  '/author/books/': typeof AuthorBooksIndexRoute
  '/author/books/$bookId/edit': typeof AuthorBooksBookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books/$bookId'
    | '/reader/$bookId'
    | '/library/'
    | '/login/'
    | '/profile/'
    | '/register/'
    | '/author/books/new'
    | '/author/books/'
    | '/author/books/$bookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books/$bookId'
    | '/reader/$bookId'
    | '/library'
    | '/login'
    | '/profile'
    | '/register'
    | '/author/books/new'
    | '/author/books'
    | '/author/books/$bookId/edit'
  id:
    | '__root__'
    | '/'
    | '/books/$bookId'
    | '/reader/$bookId'
    | '/library/'
    | '/login/'
    | '/profile/'
    | '/register/'
    | '/author/books/new'
    | '/author/books/'
    | '/author/books/$bookId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  ReaderBookIdRoute: typeof ReaderBookIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  AuthorBooksNewRoute: typeof AuthorBooksNewRoute
  AuthorBooksIndexRoute: typeof AuthorBooksIndexRoute
  AuthorBooksBookIdEditRoute: typeof AuthorBooksBookIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$bookId': {
      id: '/reader/$bookId'
      path: '/reader/$bookId'
      fullPath: '/reader/$bookId'
      preLoaderRoute: typeof ReaderBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/books/': {
      id: '/author/books/'
      path: '/author/books'
      fullPath: '/author/books/'
      preLoaderRoute: typeof AuthorBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/books/new': {
      id: '/author/books/new'
      path: '/author/books/new'
      fullPath: '/author/books/new'
      preLoaderRoute: typeof AuthorBooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/books/$bookId/edit': {
      id: '/author/books/$bookId/edit'
      path: '/author/books/$bookId/edit'
      fullPath: '/author/books/$bookId/edit'
      preLoaderRoute: typeof AuthorBooksBookIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  ReaderBookIdRoute: ReaderBookIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  AuthorBooksNewRoute: AuthorBooksNewRoute,
  AuthorBooksIndexRoute: AuthorBooksIndexRoute,
  AuthorBooksBookIdEditRoute: AuthorBooksBookIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
